### ISSUE TITLE
contributor wordcloud improvements

### ISSUE THREAD

**Issue by rsaxvc** [OpenHD/Documentation#24]
Minor. I noticed .gitbook/assets/wordcloud.svg doesn't render well in EyeOfGnome/EyeOfMate, Google Chrome, IE, or MS Edge on https://openhd.gitbook.io/open-hd/general/team under 'Additional Mentions' section, and look like this:

![image](https://user-images.githubusercontent.com/348896/230805632-7de456cb-88bc-41a7-a151-0089d2061da8.png)

I think this is due to use of a non-HTML marked foreignObject. Also, there's a copy of each font per contributor handle, but this could probably be a plain SVG.

**Comment by raphaelscholle** [comment]
oh, it should just be a simple svg, but looks like I should just use a png instead
will do so in a few minutes
